sudo: required
dist: trusty

language: go

go:
  - 1.7
  - tip
  allow_failures:
  - 1.6

os:
  - linux
  - osx
      
      
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90; fi

script:
  - gcc --version
  - g++ --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ld --version; fi
  
