sudo: required
dist: trusty

language: cpp

os:
  - linux

#cache:
#  directories:
#    - $HOME/binutils

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
#      - libxxf86vm-dev
#      - libnotify-dev
#      - binutils
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi

install:
  - gcc --version
  - g++ --version
  - ls -la /usr/lib/x86_64-linux-gnu/
#  - g++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 -fabi-compat-version=8 -c -o test.o test.cpp
#  - nm test.o | c++filt
#  - g++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 -fabi-compat-version=8 test.cpp
#  - ldd a.out
  - ld -lgtk-x11-2.0 --verbose
  - ld -lgdk-x11-2.0 --verbose
  - ld -lpangocairo-1.0 --verbose
  - ld -latk-1.0 --verbose
  - ld -lpango-1.0 --verbose

